import express from 'express';
import { postJob, getAllJobs, getJobById, getAdminJobs, updateJob } from '../controllers/job.controller.js';
import isAuthenticated from '../middlewares/isAuthenticated.js';
const router=express.Router();
router.route("/post").post(isAuthenticated,postJob);
router.route("/update/:id").put(isAuthenticated,updateJob);
router.route("/get").get(isAuthenticated,getAllJobs);
router.route("/getAdminJobs").get(isAuthenticated,getAdminJobs);
router.route("/get/:id").get(isAuthenticated,getJobById);
export default router;
